### ISSUE TITLE
Impossible to add model on multiple add

### ISSUE THREAD

**Issue by grafixinfluenz** [MichaelBelgium/LaravelShoppingcart#4]
Hi,
I encoutered an issue to affect model on multiple add. To add several items in one shot I have to use an array but the function associate doesn't work on it. I tried a lot of combinations but I can't deal with it. 
Is there any way to associate any model with an array of cartitems ?
Thanks by advance.
Best Regards,
Cyrille

**Comment by MichaelBelgium** [comment]
Not sure if I understand you completely.

So you're trying to add multiple instances of Buyable objects as array to Cart::add() ?
LIke this?

```PHP
Cart::add([
    $product,
    $product2,
    $product3
]);
```

Can you give me a code example of what you're tryingt to do?

**Comment by grafixinfluenz** [comment]
Yes that's it and in this case I can't associate Model.

Here's one example of what I tried

```
Cart::add([
                        ['id' => $product->id, 'name' => $product->title, 'qty' => $request->place, 'price' => $product->price, 'options' => ['date_id' => $dateid]],
                        ['id' => $product->id, 'name' => $product->title, 'qty' => $request->discount_place, 'price' => $product->discount_price, 'options' => ['date_id' => $dateid]]
                    ])->associate('App\Models\Product');
```
I also tried other ways but nothing is working properly.

**Comment by grafixinfluenz** [comment]
Basically I have full price and kid price for my item, I would like to add both in the same time with associate Model.

**Comment by MichaelBelgium** [comment]
Oh like that, well because you're inserting an array in the add() function, you get an array of cartitems back. You just have to loop through them.

This should be your solution:

```PHP
$addedItems = Cart::add([
    ['id' => $product->id, 'name' => $product->title, 'qty' => $request->place, 'price' => $product->price, 'options' => ['date_id' => $dateid]],
    ['id' => $product->id, 'name' => $product->title, 'qty' => $request->discount_place, 'price' => $product->discount_price, 'options' => ['date_id' => $dateid]]
]);

foreach ($addedItems as $cartItem)
{
    $cartItem->associate('App\Models\Product');
}
```

**Comment by grafixinfluenz** [comment]
I tried this way and it works but if I pick one full price and one discount price, I found in my Cart  only 1 item with quantity 2 and discount price only. It's really weird, thanks for your help :)

**Comment by grafixinfluenz** [comment]
I think I have to change my logic, I'm gonna try using options in that case..

**Comment by MichaelBelgium** [comment]
It probably replaces the first one because the second one (with the discount) has the same product id. Either yeah, you'll have to change your logic, or just give another id to the discounted product

**Comment by grafixinfluenz** [comment]
Indeed, thanks again for your help and pointing that. I'm going back to work and try to fix it ;)
